#!/bin/bash
#Failidest nimede ja paroolide võtmine. Kasutajade ja paroolide lisamine.

data=$(paste -d: $1 $2)
for row in $(paste -d: $1 $2)
do
	username=$(echo $row | awk -F":" '{print $1}')
	useradd -m -s /bin/bash $username
	echo $row | chpasswd
done
