#!/bin/bash

#Skriptist line haavalt võtmine, peaks olema var
#Loop mis jooksutab läbi lisa kasutaja

failinimi=$1

#i=1
 
while IFS= read line; do    
    i=$(( i + 1 ))
username=$(echo $line | cut -f1 -d:)
/bin/bash /root/rsha/praks2/lisa_kasutaja "$username"

addpass=$(echo $line)
echo "$addpass" | chpasswd

done < $failinimi

